/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FARMACIA;

/**
 *
 * @author Tasnim Ahmed
 */
public class CheckOut extends javax.swing.JPanel {

    /**
     * Creates new form CheckOut
     */
    public CheckOut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1210, 670));
        setPreferredSize(new java.awt.Dimension(1210, 670));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Zapfino", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Available Balance : ");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 350, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/taka.png"))); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 60, 60));

        jLabel14.setFont(new java.awt.Font("Ubuntu Mono", 1, 48)); // NOI18N
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 390, 70));

        jLabel4.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 160, 40));

        jLabel2.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Price : ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 90, 40));

        jPanel2.setBackground(new java.awt.Color(29, 32, 38));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("F A R M A C I A");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 60));

        jLabel12.setBackground(new java.awt.Color(29, 32, 38));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pharmacy.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 260, 180));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 670));

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setForeground(java.awt.Color.white);
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton10.setToolTipText("Back To Menu");
        jButton10.setBorder(null);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 70, 70));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cart.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 70, 70));

        jLabel3.setFont(new java.awt.Font("Palace Script MT", 0, 52)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Shopping Cart");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 280, 50));

        jLabel5.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("[ Quantity ]");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 400, 110, 40));

        jLabel6.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 160, 40));

        jSlider1.setBackground(new java.awt.Color(255, 255, 255));
        jSlider1.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jSlider1.setForeground(new java.awt.Color(29, 32, 38));
        jSlider1.setMajorTickSpacing(5);
        jSlider1.setMaximum(21);
        jSlider1.setMinimum(1);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setValue(10);
        add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 350, 340, -1));

        jLabel7.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Medicine Name : ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 160, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buy.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 580, 280, 80));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton10;
    public javax.swing.JButton jButton8;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
