/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FARMACIA;

/**
 *
 * @author Tasnim Ahmed
 */
public class Shop extends javax.swing.JPanel {

    /**
     * Creates new form shop
     */
    public Shop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator8 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1210, 670));
        setPreferredSize(new java.awt.Dimension(1210, 670));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator8.setBackground(new java.awt.Color(29, 32, 38));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 270, 20));

        jLabel6.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 330, 40));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ord.png"))); // NOI18N
        jButton7.setToolTipText("Place Order");
        jButton7.setBorder(null);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, 270, 70));

        jLabel11.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 330, 40));

        jSeparator10.setBackground(new java.awt.Color(29, 32, 38));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 270, 20));

        jSeparator9.setBackground(new java.awt.Color(29, 32, 38));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 270, 20));

        jPanel2.setBackground(new java.awt.Color(29, 32, 38));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 210, 20));

        jTextField1.setBackground(new java.awt.Color(29, 32, 38));
        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(null);
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 260, 50));

        jButton2.setBackground(new java.awt.Color(29, 32, 38));
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        jButton2.setToolTipText("Search For Medicine");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 70, 70));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("F A R M A C I A");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 60));

        jLabel20.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("[Search By Name]");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 260, 50));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 670));

        jLabel9.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 330, 40));

        jLabel8.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Medicine Name");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 210, 40));

        jSeparator14.setBackground(new java.awt.Color(29, 32, 38));
        add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 270, 20));

        jLabel2.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Available (PCS)");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 200, 40));

        jLabel7.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 330, 40));

        jLabel18.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Medicine ID");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 180, 40));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rsz_1medical.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 70, 70));

        jSeparator13.setBackground(new java.awt.Color(29, 32, 38));
        add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 270, 20));

        jLabel5.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 330, 40));

        jLabel4.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Manufactured By");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 200, 40));

        jLabel10.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Price (Taka)");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, 270, 40));

        jLabel3.setFont(new java.awt.Font("Palace Script MT", 0, 52)); // NOI18N
        jLabel3.setText("Medicine Arena");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 280, 40));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setForeground(java.awt.Color.white);
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton9.setToolTipText("Back To Menu");
        jButton9.setBorder(null);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 70, 70));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton7;
    public javax.swing.JButton jButton8;
    public javax.swing.JButton jButton9;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
